name: OMS_APP
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  dio: ^5.4.0
  flutter_svg: ^2.0.7 
  fl_chart: ^0.63.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.jpg 
    - assets/icon/facebook.png
    - assets/icon/google.png   # <-- your launcher icon
    - assets/man.jpg
    - assets/chart.jpg
    - assets/frame.svg
    - assets/icon/tcs.png 
    - assets/icon/bluex.jpeg
    - assets/icon/graph.png
    - assets/icon/create.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"
